name: Update Experience Years

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes
        run: |
          git pull origin main --rebase

      - name: Calculate Rounded Experience Years
        run: |
          START_DATE="2021-05-05"
          TODAY=$(date +%s)
          START=$(date -d "$START_DATE" +%s)
          DIFF_DAYS=$(( (TODAY - START) / 86400 ))
          YEARS=$(echo "$DIFF_DAYS / 365" | bc)  # Integer division
          sed -i "s/{{experience}}/${YEARS}/" README.md

      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "📈 Update experience years to ${YEARS}" || echo "No changes to commit"
          git push origin main
